'use client'
import { GitPullRequest } from "lucide-react";
import Image from "next/image";
import CursorLogo from "@/public/images/cursor_logo.png";
import ClaudeLogo from "@/public/images/Claude_AI_symbol.svg";
import SlackLogo from "@/public/images/slack.png";
import LinearLogo from "@/public/images/linear.png";
import GithubLogo from "@/public/images/github_logo.png";

const NAVY = "#1e3a5f";

function SlackMockup() {
  return (
    <div className="rounded border border-gray-200 bg-white p-3 font-sans">
      <div className="flex items-center gap-1.5 mb-2">
        <Image src={SlackLogo} alt="Slack" width={12} height={12} className="object-contain" />
        <p className="text-[10px] font-semibold text-gray-400">#nexus-alerts</p>
      </div>
      <div className="flex items-start gap-2">
        <div className="w-5 h-5 rounded-sm flex-shrink-0 flex items-center justify-center mt-0.5" style={{ background: NAVY }}>
          <span className="text-white text-[8px] font-bold">N</span>
        </div>
        <div className="min-w-0">
          <p className="text-[10px] font-semibold text-gray-800 leading-tight">Tool hallucination detected</p>
          <p className="text-[9px] text-gray-400 mt-0.5">checkout-agent · just now</p>
          <p className="text-[9px] text-gray-500 mt-1 leading-relaxed">Prompt v4.2 removed inventory fallback on line 14</p>
          <span className="inline-block mt-1.5 text-[9px] font-semibold" style={{ color: NAVY }}>View in Nexus →</span>
        </div>
      </div>
    </div>
  );
}

function LinearMockup() {
  return (
    <div className="rounded border border-gray-200 bg-white p-3 mb-5">
      <div className="flex items-center justify-between mb-2">
        <div className="flex items-center gap-1.5">
          <Image src={LinearLogo} alt="Linear" width={12} height={12} className="object-contain" />
          <span className="text-[9px] font-mono text-gray-400">NEX-247</span>
        </div>
        <span className="text-[9px] px-1.5 py-0.5 rounded-sm font-medium bg-red-50 text-red-500">High</span>
      </div>
      <p className="text-[10px] font-semibold text-gray-800 leading-snug mb-2">Tool hallucination in checkout flow</p>
      <div className="space-y-1">
        <div className="flex items-center gap-1.5 text-[9px] text-gray-400">
          <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 flex-shrink-0" />
          Root-cause attached
        </div>
        <div className="flex items-center gap-1.5 text-[9px] text-gray-400">
          <span className="w-1.5 h-1.5 rounded-full bg-blue-400 flex-shrink-0" />
          Logs &amp; traces linked
        </div>
      </div>
    </div>
  );
}

function McpMockup() {
  return (
    <div className="rounded border border-gray-200 bg-gray-50 p-3 flex items-center justify-center gap-6 h-full">
      <div className="flex flex-col items-center gap-1.5">
        <div className="w-10 h-10 rounded-lg bg-white border border-gray-200 flex items-center justify-center shadow-sm">
          <Image src={CursorLogo} alt="Cursor" width={24} height={24} className="object-contain" style={{ filter: "invert(1)" }} />
        </div>
        <span className="text-[9px] text-gray-500">Cursor</span>
      </div>

      <div className="flex flex-col items-center gap-1.5">
        <div className="w-10 h-10 rounded-lg bg-white border border-gray-200 flex items-center justify-center shadow-sm">
          <Image src={ClaudeLogo} alt="Claude Code" width={24} height={24} className="object-contain" />
        </div>
        <span className="text-[9px] text-gray-500">Claude Code</span>
      </div>
    </div>
  );
}

function PrMockup() {
  return (
    <div className="rounded border border-gray-200 bg-white p-3 mb-5">
      <div className="flex items-center gap-1.5 mb-2">
        <Image src={GithubLogo} alt="GitHub" width={12} height={12} className="object-contain" style={{ filter: "invert(1)" }} />
        <GitPullRequest className="w-3 h-3 text-emerald-500 flex-shrink-0" />
        <span className="text-[10px] font-semibold text-gray-800 truncate">fix: tool selection fallback</span>
      </div>
      <div className="flex items-center gap-2 mb-2">
        <span className="text-[9px] font-mono text-emerald-600">+3</span>
        <span className="text-[9px] font-mono text-red-500">−1</span>
        <span className="text-[9px] text-gray-400">checkout/agent.py</span>
      </div>
      <p className="text-[9px] text-gray-400">Auto-generated by Nexus · ready to merge</p>
    </div>
  );
}

const ACTIONS = [
  {
    mockup: <SlackMockup />,
    title: "Slack Alerts",
    description: "Get notified the moment a silent failure is detected, straight to the right channel with full context.",
  },
  {
    mockup: <LinearMockup />,
    title: "Linear Tickets",
    description: "Auto-create tickets with root-cause analysis, logs, and reproduction steps so your team can act immediately.",
  },
  {
    mockup: <McpMockup />,
    title: "Nexus MCP",
    description: "Plug Nexus MCP into Claude Code or Cursor and jump straight into fixing with full issue context loaded without needing to do additional investigation",
  },
  {
    mockup: <PrMockup />,
    title: "Automated PRs",
    description: "Ship code fixes automatically. Nexus drafts pull requests with the changes needed to resolve the issue.",
  },
];

export default function IssueAction() {
  return (
    <section className="relative">
      <div className="mx-auto max-w-6xl px-4 sm:px-6">
        <div className="py-12 md:py-20">
          {/* Header */}
          <div className="text-center max-w-2xl mx-auto mb-10 md:mb-14">
            <div className="flex items-center justify-center gap-2 mb-4">
              <div className="h-1 w-1 rounded-full" style={{ background: NAVY }} />
              <span className="text-sm font-medium text-gray-500">Take Action</span>
            </div>
            <h2 className="font-nacelle text-2xl font-semibold text-gray-900 md:text-3xl lg:text-4xl mb-4">
              Fix failures fast
            </h2>
            <p className="text-md text-gray-600 leading-relaxed">
              Operate with complete context and ship solutions faster before more users get impacted
            </p>
          </div>

          {/* 4-column grid, sharp corners, outer black border, inner dividers */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 border border-gray-900">
            {ACTIONS.map((action, i) => {
              return (
              <div
                key={action.title}
                className={`p-5 md:p-6 flex flex-col bg-white ${
                  i < 3 ? "border-b border-gray-900 lg:border-b-0 lg:border-r" : ""
                } ${i === 1 ? "sm:border-r sm:border-gray-900" : ""}`}
              >
                {/* Fixed-height mockup, fades top to bottom */}
                <div
                  className="h-[130px] overflow-hidden mb-4"
                  style={{ maskImage: "linear-gradient(to bottom, black 40%, transparent 100%)", WebkitMaskImage: "linear-gradient(to bottom, black 40%, transparent 100%)" }}
                >
                  {action.mockup}
                </div>
                <h3 className="font-nacelle text-lg font-semibold text-gray-900 mb-2">
                  {action.title}
                </h3>
                <p className="text-sm text-gray-600 leading-relaxed">
                  {action.description}
                </p>
              </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
}
